<?php

namespace App\Controller;

use App\Entity\TexteAccueil;
use App\Form\EcoleTexteType;
use App\Form\GestionTexteType;
use App\Entity\TextePresentationEcole;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;



class AdminTexteController extends AbstractController
{
     /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/admin/texte", name="admin_texte")
     * 
     */
    public function indexGestionTexte(Request $request)
    {
        $texteAccueil = new TexteAccueil();

        $formAccueil = $this->createForm(GestionTexteType::class, $texteAccueil);
        $formAccueil->handleRequest($request);
      
        if ($formAccueil->isSubmitted() && $formAccueil->isValid()) {
            $file1 = $texteAccueil->getPhoto();
            $fileName1 = $this->generateUniqueFileName().'.'.$file1->guessExtension();

            try {
                $file1->move($this->getParameter('photoSection_directory'),
                $fileName1);
            }

            catch (FileException $e) {

            }

            $texteAccueil->setPhoto($fileName1);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($texteAccueil);
            $entityManager->flush();
            return $this->redirectToRoute('admin_texte');
        }
    

        $texteEcole = new TextePresentationEcole();

     
        $file2 = $texteEcole->getPhoto();
           
  
        $formEcole = $this->createForm(EcoleTexteType::class);
        $formEcole->handleRequest($request);

        if ($formEcole->isSubmitted() && $formEcole->isValid()) {

            $fileName2 = $this->generateUniqueFileName().'.'.$file2->guessExtension();
             

            try {
                $file2->move($this->getParameter('photoSection_directory'),
                $fileName2);
            }

            catch (FileException $e) {

            }

            $texteEcole->setPhoto($fileName2);
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($texteEcole);
            $entityManager->flush();

            return $this->redirectToRoute('admin_texte');
        }


        return $this->render('admin_texte/index.html.twig', [
            'formAccueil' => $formAccueil->createView(),
            'formEcole' => $formEcole->createView()
        ]);
    }
}
